name: staffManager
version: '${version}'
main: me.betun.staffmanager.StaffManager
api-version: '1.20'
author: Betun04
depend: [ProtocolLib]
commands:
  staffmanager:
    description: "Comando principal de StaffManager"
    usage: /<command>
    aliases:
      - sm
      - staffm
      - smanager
    permission: op