name: staffManager
version: '${version}'
main: me.betun.staffmanager.StaffManager
api-version: '1.20'
author: Betun04
commands:
  saveInv:
    description: "Guarda inventarios"
    usage: /<command>
    aliases:
      - savei
      - sinv
    permission: op